version: '3'
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "${PG_PASS}"
    volumes:
      - postgres:/var/lib/postgresql/data

  cloudflare-dyndns:
    build: cloudflare-dyndns/
    restart: always
    environment:
      CF_API_TOKEN: "${CF_API_TOKEN}"
      CF_DOMAIN: "${CF_DOMAIN}"
      CF_RECORD: "${CF_RECORD}"

  certbot-auto:
    build: certbot-cloudflare-auto/
    volumes:
      - letsencrypt-etc:/etc/letsencrypt
      - letsencrypt-lib:/var/lib/letsencrypt
    restart: always
    environment:
      API_TOKEN: "${CF_API_TOKEN}"
    command:
      - "certonly"
      - "--agree-tos"
      - "-d"
      - "${DOMAIN}"
      - "-m"
      - "${LE_EMAIL}"
      - "--dns-cloudflare"
      - "--dns-cloudflare-credentials=/etc/cloudflare_credentials.ini"
      - "-n"

  redis:
    image: redis:alpine
    restart: always

  nextcloud:
    image: nextcloud:fpm-alpine
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${PG_PASS}"
      REDIS_HOST: redis
    volumes:
      - nextcloud:/var/www/html

  nextcloud_cron:
    image: nextcloud:fpm-alpine
    restart: always
    depends_on:
      - postgres
      - redis
    entrypoint: /cron.sh
    volumes:
      - nextcloud:/var/www/html

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - letsencrypt-etc:/etc/letsencrypt
      - nextcloud:/var/www/html:ro
    ports:
      - "${HTTPS_LISTEN_ADDR}:8443:443"
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      DOMAIN: "${DOMAIN}"

  onlyoffice:
    image: onlyoffice/documentserver
    restart: always
    depends_on:
      - onlyoffice-postgres
      - rabbitmq
    environment:
      DB_HOST: onlyoffice-postgres
      DB_NAME: postgres
      DB_USER: postgres
      DB_PWD: "${PG_PASS}"
      DB_PORT: 5432
      AMQP_URI: amqp://guest:guest@rabbitmq

  onlyoffice-postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "${PG_PASS}"

  rabbitmq:
    image: rabbitmq
    restart: always

volumes:
  nextcloud:
    external: true
  letsencrypt-etc:
    external: true
  letsencrypt-lib:
    external: true
  postgres:
    external: true
  
