version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${PG_PASS}"
    volumes:
      - postgres:/var/lib/postgresql/data

  cloudflare-dyndns:
    build: cloudflare-dyndns/
    restart: always
    environment:
      CF_API_TOKEN: "${CF_API_TOKEN}"
      CF_DOMAIN: "${CF_DOMAIN}"
      CF_RECORD: "${CF_RECORD}"

  certbot-auto:
    build: certbot-cloudflare-auto/
    volumes:
      - letsencrypt-etc:/etc/letsencrypt
      - letsencrypt-lib:/var/lib/letsencrypt
    restart: always
    environment:
      API_TOKEN: "${CF_API_TOKEN}"
    command:
      - "certonly"
      - "--agree-tos"
      - "-d"
      - "${DOMAIN}"
      - "-m"
      - "${LE_EMAIL}"
      - "--dns-cloudflare"
      - "--dns-cloudflare-credentials=/etc/cloudflare_credentials.ini"
      - "-n"

  nextcloud:
    image: nextcloud
    restart: always
    environment:
      TRUSTED_PROXIES: nginx
      APACHE_DISABLE_REWRITE_IP: 1
    volumes:
      - nextcloud:/var/www/html

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/conf.template
      - letsencrypt-etc:/etc/letsencrypt
    ports:
      - "${HTTPS_LISTEN_ADDR}:8443:443"
    environment:
      DOMAIN: "${DOMAIN}"
    command: /bin/bash -c "envsubst '$${DOMAIN}' < /etc/nginx/conf.d/conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

volumes:
  nextcloud:
    external: true
  letsencrypt-etc:
    external: true
  letsencrypt-lib:
    external: true
  postgres:
    external: true
